apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: cloudmart

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: YOUR_BACKEND_ECR_REPOSITORY:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: cloudmart-config

            - secretRef:
                name: cloudmart-secret

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 30
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 10
            periodSeconds: 10